version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      opentelemetry:
        patterns:
          - go.opentelemetry.io/*
      pion:
        patterns:
          - github.com/pion/*
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

