// SPDX-License-Identifier: Apache-2.0

package telemetry

// LiveKit attributes containing conversational/user data deliberately include
// a dot-delimited "pii" segment. LiveKit Cloud's collector uses that marker for
// recursive redaction. Never place such content in span or event names.
const (
	AttrSpeechID                   = "lk.speech_id"
	AttrAgentLabel                 = "lk.agent_label"
	AttrStartTime                  = "lk.start_time"
	AttrEndTime                    = "lk.end_time"
	AttrRetryCount                 = "lk.retry_count"
	AttrProviderRequestIDs         = "lk.provider_request_ids"
	AttrParticipantID              = "lk.participant_id"
	AttrParticipantIdentity        = "lk.pii.participant_identity"
	AttrParticipantKind            = "lk.participant_kind"
	AttrJobID                      = "lk.job_id"
	AttrAgentName                  = "lk.agent_name"
	AttrCloudAgentID               = "lk.cloud_agent_id"
	AttrDeploymentID               = "lk.deployment_id"
	AttrRoomName                   = "lk.pii.room_name"
	AttrSessionOptions             = "lk.session_options"
	AttrAgentTurnID                = "lk.generation_id"
	AttrAgentParentTurnID          = "lk.parent_generation_id"
	AttrUserInput                  = "lk.pii.user_input"
	AttrInstructions               = "lk.pii.instructions"
	AttrSpeechInterrupted          = "lk.interrupted"
	AttrChatContext                = "lk.pii.chat_ctx"
	AttrFunctionTools              = "lk.function_tools"
	AttrProviderTools              = "lk.provider_tools"
	AttrToolSets                   = "lk.tool_sets"
	AttrResponseText               = "lk.pii.response.text"
	AttrResponseFunctionCalls      = "lk.pii.response.function_calls"
	AttrResponseTTFT               = "lk.response.ttft"
	AttrFunctionToolID             = "lk.function_tool.id"
	AttrFunctionToolName           = "lk.function_tool.name"
	AttrFunctionToolArguments      = "lk.pii.function_tool.arguments"
	AttrFunctionToolIsError        = "lk.function_tool.is_error"
	AttrFunctionToolOutput         = "lk.pii.function_tool.output"
	AttrTTSInputText               = "lk.pii.input_text"
	AttrTTSStreaming               = "lk.tts.streaming"
	AttrTTSLabel                   = "lk.tts.label"
	AttrResponseTTFB               = "lk.response.ttfb"
	AttrEOUProbability             = "lk.eou.probability"
	AttrEOUUnlikelyThreshold       = "lk.eou.unlikely_threshold"
	AttrEOUDelay                   = "lk.eou.endpointing_delay"
	AttrEOULanguage                = "lk.eou.language"
	AttrEOUSource                  = "lk.eou.source"
	AttrEOUFromCache               = "lk.eou.from_cache"
	AttrEOUDetectionDelay          = "lk.eou.detection_delay"
	AttrUserTranscript             = "lk.pii.user_transcript"
	AttrTranscriptConfidence       = "lk.transcript_confidence"
	AttrTranscriptionDelay         = "lk.transcription_delay"
	AttrEndOfTurnDelay             = "lk.end_of_turn_delay"
	AttrAMDCategory                = "lk.amd.category"
	AttrAMDReason                  = "lk.amd.reason"
	AttrAMDIsMachine               = "lk.amd.is_machine"
	AttrAMDInterruptOnMachine      = "lk.amd.interrupt_on_machine"
	AttrAMDSpeechDuration          = "lk.amd.speech_duration"
	AttrAMDDelay                   = "lk.amd.delay"
	AttrAMDTranscript              = "lk.pii.amd.transcript"
	AttrIsInterruption             = "lk.is_interruption"
	AttrInterruptionProbability    = "lk.interruption.probability"
	AttrInterruptionTotalDuration  = "lk.interruption.total_duration"
	AttrInterruptionPredictionTime = "lk.interruption.prediction_duration"
	AttrInterruptionDetectionDelay = "lk.interruption.detection_delay"
	AttrLLMMetrics                 = "lk.llm_metrics"
	AttrTTSMetrics                 = "lk.tts_metrics"
	AttrRealtimeModelMetrics       = "lk.realtime_model_metrics"
	AttrEndToEndLatency            = "lk.e2e_latency"

	AttrGenAIOperationName         = "gen_ai.operation.name"
	AttrGenAIRequestModel          = "gen_ai.request.model"
	AttrGenAIProviderName          = "gen_ai.provider.name"
	AttrGenAIUsageInputTokens      = "gen_ai.usage.input_tokens"
	AttrGenAIUsageOutputTokens     = "gen_ai.usage.output_tokens"
	AttrGenAIUsageInputTextTokens  = "gen_ai.usage.input_text_tokens"
	AttrGenAIUsageInputAudioTokens = "gen_ai.usage.input_audio_tokens"
	AttrGenAIUsageInputCached      = "gen_ai.usage.input_cached_tokens"
	AttrGenAIUsageOutputTextTokens = "gen_ai.usage.output_text_tokens"
	AttrGenAIUsageOutputAudio      = "gen_ai.usage.output_audio_tokens"

	EventGenAISystemMessage    = "gen_ai.system.message"
	EventGenAIUserMessage      = "gen_ai.user.message"
	EventGenAIAssistantMessage = "gen_ai.assistant.message"
	EventGenAIToolMessage      = "gen_ai.tool.message"
	EventGenAIChoice           = "gen_ai.choice"

	AttrExceptionTrace   = "exception.stacktrace"
	AttrExceptionType    = "exception.type"
	AttrExceptionMessage = "exception.message"

	AttrLangfuseCompletionStartTime = "langfuse.observation.completion_start_time"
)
